/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2026-04-09 08:16:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import pms.utils.NotificationService;
import pms.utils.NotificationService.Notification;

public final class shared_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("pms.utils.NotificationService");
    _jspx_imports_classes.add("pms.utils.NotificationService.Notification");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Lấy user từ session
    pms.model.UserDTO headerUser = (pms.model.UserDTO) session.getAttribute("user");
    String pageTitle = request.getAttribute("pageTitle") != null ? (String) request.getAttribute("pageTitle") : "Bảng điều khiển";
    
    String notificationUsername = headerUser != null ? headerUser.getUsername() : null;
    List<Notification> headerNotifications = NotificationService.getNotifications(notificationUsername);
    int unreadCount = NotificationService.getUnreadCount(notificationUsername);
    
    Boolean sessionDark = (Boolean) session.getAttribute("darkMode");
    boolean isDarkMode = sessionDark != null ? sessionDark : false;
    String lang = session.getAttribute("lang") != null ? (String) session.getAttribute("lang") : "vi";
    String userName = headerUser != null ? headerUser.getUsername() : "User";
    String userRole = headerUser != null ? headerUser.getRole() : "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    @media (min-width: 1024px) {\r\n");
      out.write("        #mainWrapper.sidebar-open {\r\n");
      out.write("            margin-left: 280px !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #mainWrapper.sidebar-closed {\r\n");
      out.write("            margin-left: 0 !important;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Cố Định - Shared Component -->\r\n");
      out.write("<header class=\"main-header sticky top-0 z-20 h-16 bg-white/95 dark:bg-slate-800/95 border-b border-slate-200 dark:border-slate-700 backdrop-blur pl-2 pr-4 lg:pl-2 lg:pr-6 flex items-center justify-between shadow-sm relative\">\r\n");
      out.write("    <!-- Left: Menu + Title -->\r\n");
      out.write("    <div class=\"flex items-center gap-2 min-w-0\">\r\n");
      out.write("        <button id=\"menuToggle\" onclick=\"toggleSidebar()\" class=\"w-10 h-10 flex items-center justify-center rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors shrink-0\" title=\"Mở/đóng menu trái\">\r\n");
      out.write("            <svg class=\"w-5 h-5 text-slate-600 dark:text-slate-300\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div>\r\n");
      out.write("            <h1 class=\"text-lg font-semibold text-slate-900 dark:text-slate-100\">");
      out.print( pageTitle );
      out.write("</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Center: Search Box -->\r\n");
      out.write("    <div class=\"hidden md:flex flex-1 max-w-xl mx-4\">\r\n");
      out.write("        <div class=\"search-box relative flex items-center w-full rounded-full px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-sm\">\r\n");
      out.write("            <svg class=\"w-4 h-4 text-slate-400 dark:text-slate-500 mr-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                id=\"globalSearch\"\r\n");
      out.write("                placeholder=\"Tìm kiếm...\"\r\n");
      out.write("                class=\"flex-1 bg-transparent outline-none text-sm text-slate-700 dark:text-slate-200 placeholder:text-slate-400 dark:placeholder:text-slate-500\"\r\n");
      out.write("                onkeyup=\"handleGlobalSearch(event)\"\r\n");
      out.write("            />\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right: Language + Dark Mode + Notifications + User -->\r\n");
      out.write("    <div class=\"flex items-center gap-2\">\r\n");
      out.write("        <!-- Language Toggle -->\r\n");
      out.write("        <div class=\"flex items-center rounded-lg overflow-hidden border border-slate-200 dark:border-slate-700 h-10 bg-white dark:bg-slate-800\">\r\n");
      out.write("            <a href=\"?lang=vi\" class=\"px-3 py-1.5 text-xs font-medium flex items-center ");
      out.print( "vi".equals(lang) ? "bg-teal-500 text-white" : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700" );
      out.write("\">VI</a>\r\n");
      out.write("            <a href=\"?lang=en\" class=\"px-3 py-1.5 text-xs font-medium flex items-center ");
      out.print( "en".equals(lang) ? "bg-teal-500 text-white" : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700" );
      out.write("\">EN</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Dark Mode Toggle -->\r\n");
      out.write("        <button onclick=\"toggleDarkMode()\" class=\"w-10 h-10 flex items-center justify-center rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors\" title=\"Chế độ tối\">\r\n");
      out.write("            <svg id=\"moonIcon\" class=\"w-5 h-5 text-slate-600 dark:text-slate-300 ");
      out.print( isDarkMode ? "hidden" : "" );
      out.write("\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <svg id=\"sunIcon\" class=\"w-5 h-5 text-slate-600 dark:text-slate-300 ");
      out.print( isDarkMode ? "" : "hidden" );
      out.write("\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </button>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Notification Bell -->\r\n");
      out.write("        <button id=\"notifBtn\" onclick=\"toggleNotificationPanel()\" class=\"relative w-10 h-10 flex items-center justify-center rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors\">\r\n");
      out.write("            <svg class=\"w-5 h-5 text-slate-600 dark:text-slate-300\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            ");
 if (unreadCount > 0) { 
      out.write("\r\n");
      out.write("            <span id=\"notifBadge\" class=\"notif-badge absolute -top-1 -right-1 min-w-[20px] h-5 px-1 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center\">\r\n");
      out.write("                ");
      out.print( unreadCount > 9 ? "9+" : unreadCount );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <span id=\"notifBadge\" class=\"notif-badge absolute -top-1 -right-1 min-w-[20px] h-5 px-1 bg-red-500 text-white text-[10px] font-bold rounded-full hidden items-center justify-center\">0</span>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("        \r\n");
      out.write("        <!-- User: text chào mừng + dropdown -->\r\n");
      out.write("        <button id=\"userDropdownBtn\" onclick=\"toggleUserDropdown()\" class=\"flex items-center gap-2 px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors\">\r\n");
      out.write("            <span class=\"hidden sm:block text-sm font-medium text-slate-700 dark:text-slate-200\">Xin chào, ");
      out.print( userName );
      out.write("</span>\r\n");
      out.write("            <svg class=\"w-4 h-4 text-slate-400 dark:text-slate-500 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 9l-7 7-7-7\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Notification Panel -->\r\n");
      out.write("<div id=\"notifPanel\" class=\"absolute right-4 top-16 w-80 bg-white dark:bg-slate-800 rounded-xl shadow-xl border border-slate-200 dark:border-slate-700 hidden z-50 overflow-hidden\">\r\n");
      out.write("    <div class=\"p-4 border-b border-slate-100 dark:border-slate-700 flex items-center justify-between\">\r\n");
      out.write("        <h3 class=\"font-semibold text-slate-900 dark:text-slate-100\">Thông báo</h3>\r\n");
      out.write("        ");
 if (notificationUsername != null && unreadCount > 0) { 
      out.write("\r\n");
      out.write("        <button type=\"button\" onclick=\"markAllNotificationsRead()\" class=\"text-xs text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300\">Đánh dấu đã đọc</button>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"notifList\" class=\"max-h-80 overflow-y-auto\">\r\n");
      out.write("        ");
 if (headerNotifications.isEmpty()) { 
      out.write("\r\n");
      out.write("        <div class=\"p-8 text-center text-slate-400 dark:text-slate-500\" id=\"notifEmptyState\">\r\n");
      out.write("            <svg class=\"w-12 h-12 mx-auto mb-2 opacity-50\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <p>Chưa có thông báo nào</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("        ");
 for (Notification n : headerNotifications) { 
      out.write("\r\n");
      out.write("        <a href=\"");
      out.print( n.getLink() );
      out.write("\" data-notification-item=\"true\" data-notification-id=\"");
      out.print( n.getId() );
      out.write("\" class=\"block p-4 border-b border-slate-50 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700/60 transition-colors ");
      out.print( n.isRead() ? "opacity-60" : "" );
      out.write("\" onclick=\"return handleNotificationClick(event, '");
      out.print( n.getId() );
      out.write("', '");
      out.print( n.getLink() );
      out.write("')\">\r\n");
      out.write("            <p data-notification-title=\"true\" class=\"text-sm font-semibold text-slate-900 dark:text-slate-100 ");
      out.print( n.isRead() ? "" : "text-teal-600 dark:text-teal-400" );
      out.write('"');
      out.write('>');
      out.print( n.getTitle() );
      out.write("</p>\r\n");
      out.write("            <p class=\"text-xs text-slate-500 dark:text-slate-400 mt-0.5\">");
      out.print( n.getMessage() );
      out.write("</p>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- User Dropdown -->\r\n");
      out.write("<div id=\"userDropdown\" class=\"absolute right-4 top-16 w-56 bg-white dark:bg-slate-800 rounded-xl shadow-xl border border-slate-200 dark:border-slate-700 hidden z-50\">\r\n");
      out.write("    <div class=\"p-4 border-b border-slate-100 dark:border-slate-700\">\r\n");
      out.write("        <p class=\"font-semibold text-slate-900 dark:text-slate-100\">");
      out.print( userName );
      out.write("</p>\r\n");
      out.write("        ");
 if (userRole != null && !userRole.isEmpty()) { 
      out.write("\r\n");
      out.write("        <p class=\"mt-1 text-xs text-slate-500 dark:text-slate-400 uppercase tracking-wide\">");
      out.print( userRole );
      out.write("</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"p-2\">\r\n");
      out.write("        <a href=\"profile.jsp\" class=\"flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors\">\r\n");
      out.write("            <span class=\"text-sm text-slate-700 dark:text-slate-200\">Hồ sơ cá nhân</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"UserController?action=logout\" class=\"flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors\">\r\n");
      out.write("            <span class=\"text-sm text-red-600 font-medium\">Đăng xuất</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
