/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2026-04-09 08:16:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shared_002dsidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 
    // Lấy user từ session
    pms.model.UserDTO sidebarUser = (pms.model.UserDTO) session.getAttribute("user");
    String activePage = request.getAttribute("activePage") != null ? (String) request.getAttribute("activePage") : "";
    String userName = sidebarUser != null ? sidebarUser.getUsername() : "User";
    String userRole = sidebarUser != null ? sidebarUser.getRole() : "";
    String normalizedRole = userRole != null ? userRole.trim().toLowerCase() : "";
    boolean isAdmin = "admin".equalsIgnoreCase(normalizedRole);
    boolean isWorker = "employee".equalsIgnoreCase(normalizedRole)
            || "worker".equalsIgnoreCase(normalizedRole)
            || "user".equalsIgnoreCase(normalizedRole);
    boolean canViewDashboard = isAdmin || isWorker;
    boolean canViewWork = isAdmin || isWorker;
    boolean canViewReports = isAdmin || isWorker;
    boolean canManageData = isAdmin;
    boolean canManageSystem = isAdmin;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar Cố Định - Shared Component -->\r\n");
      out.write("<aside id=\"sidebar\" class=\"sidebar-fixed w-[280px] shrink-0 bg-slate-900 text-white flex flex-col h-screen shadow-2xl shadow-slate-950/40\">\r\n");
      out.write("    <!-- Logo Cố Định -->\r\n");
      out.write("    <div class=\"sidebar-header h-16 flex items-center gap-3 px-5 border-b border-slate-700\">\r\n");
      out.write("        <div class=\"w-10 h-10 rounded-xl bg-teal-500 flex items-center justify-center shrink-0\">\r\n");
      out.write("            <svg class=\"w-6 h-6 text-white\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"min-w-0\">\r\n");
      out.write("            <p class=\"font-bold text-sm truncate\">Hệ thống PMS</p>\r\n");
      out.write("            <p class=\"text-xs text-slate-400 truncate\">Quản lý sản xuất</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Navigation Scroll Riêng -->\r\n");
      out.write("    <nav class=\"sidebar-nav flex-1 py-4 px-3 space-y-1\">\r\n");
      out.write("        ");
 if (canViewDashboard) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider\">Tổng Quan</p>\r\n");
      out.write("        <a href=\"DashboardController\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "dashboard".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z\"/></svg>\r\n");
      out.write("            Bảng điều khiển\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (canViewWork) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Công Việc</p>\r\n");
      out.write("        <a href=\"MainController?action=listWorkOrder\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "workorder".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"/></svg>\r\n");
      out.write("            Lệnh sản xuất\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"WorkOrderController?action=calendar\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "calendar".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z\"/></svg>\r\n");
      out.write("            Lịch sản xuất\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("        <a href=\"KanbanController\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "kanban".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7\"/></svg>\r\n");
      out.write("            Bảng tiến độ\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (canViewReports) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Báo Cáo</p>\r\n");
      out.write("        <a href=\"ProductionLogController\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "productionlog".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("            Nhật ký sản xuất\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"QcController?action=list\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "qc".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("            Kiểm tra chất lượng\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (isWorker) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Vật Tư</p>\r\n");
      out.write("        <a href=\"MainController?action=listPurchaseOrder\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "purchaseorder".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z\"/></svg>\r\n");
      out.write("            Đề nghị nhập vật tư\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (canManageData) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Quản Lý</p>\r\n");
      out.write("        <a href=\"MainController?action=listBOM\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "bom".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10\"/></svg>\r\n");
      out.write("            Công thức BOM\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"MainController?action=listPurchaseOrder\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "purchaseorder".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z\"/></svg>\r\n");
      out.write("            Đề nghị nhập vật tư\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"MainController?action=listBill\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "bill".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z\"/></svg>\r\n");
      out.write("            Quản lý hóa đơn\r\n");
      out.write("        </a>\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Danh Mục</p>\r\n");
      out.write("        <a href=\"ItemController?action=list\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "item".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4\"/></svg>\r\n");
      out.write("            Vật tư / sản phẩm\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"CustomerController?action=listCustomer\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "customer".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z\"/></svg>\r\n");
      out.write("            Khách hàng\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"SupplierController?action=listSupplier\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "supplier".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4\"/></svg>\r\n");
      out.write("            Nhà cung cấp\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"listRouting.jsp\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "routing".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01\"/></svg>\r\n");
      out.write("            Quy trình (Routing)\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"MainController?action=listRoutingStep\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "routingstep".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01\"/></svg>\r\n");
      out.write("            Công đoạn chi tiết\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"DefectController?action=listDefectReason\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "defect".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z\"/></svg>\r\n");
      out.write("            Lý do lỗi\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if (canManageSystem) { 
      out.write("\r\n");
      out.write("        <p class=\"px-3 py-2 text-xs font-semibold text-slate-400 uppercase tracking-wider mt-4\">Hệ Thống</p>\r\n");
      out.write("        <a href=\"UserController?action=list\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "user".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z\"/></svg>\r\n");
      out.write("            Người dùng\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"AdminController\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( "smtp".equals(activePage) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 8l7.89 4.26a2 2 0 002.22 0L21 8m-18 8h18a2 2 0 002-2V8a2 2 0 00-2-2H3a2 2 0 00-2 2v6a2 2 0 002 2z\"/></svg>\r\n");
      out.write("            Cấu hình SMTP\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"PaymentController?action=list\" class=\"flex items-center gap-3 px-3 py-2.5 rounded-xl ");
      out.print( ("payment".equals(activePage) || "payment-config".equals(activePage)) ? "bg-teal-500/20 text-teal-300 font-semibold shadow-inner shadow-teal-900/30 ring-1 ring-teal-400/20" : "text-slate-300 hover:bg-slate-800/90 hover:text-white" );
      out.write(" transition-all duration-200\">\r\n");
      out.write("            <svg class=\"w-5 h-5 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm-5-5h.01M17 16h.01\"/></svg>\r\n");
      out.write("            Quản lý thanh toán\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- User Section Cố Định: avatar + tên + role + dropdown + nút cài đặt -->\r\n");
      out.write("    <div class=\"sidebar-footer border-t border-slate-700 p-4 relative\">\r\n");
      out.write("        <div class=\"flex items-center gap-3\">\r\n");
      out.write("            <button type=\"button\" onclick=\"toggleSidebarUserMenu()\" class=\"flex-1 flex items-center gap-3 min-w-0 text-left rounded-xl py-2.5 px-2.5 hover:bg-slate-800/90 transition-all duration-200\">\r\n");
      out.write("                <div class=\"w-10 h-10 rounded-full bg-teal-500 flex items-center justify-center font-bold shrink-0\">\r\n");
      out.write("                    ");
      out.print( userName.length() > 0 ? userName.substring(0,1).toUpperCase() : "U" );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex-1 min-w-0\">\r\n");
      out.write("                    <p class=\"font-semibold text-sm truncate\">");
      out.print( userName );
      out.write("</p>\r\n");
      out.write("                    <p class=\"text-xs text-slate-400 truncate\">");
      out.print( userRole );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <svg class=\"w-4 h-4 text-slate-400 shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 9l-7 7-7-7\"/></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"sidebarUserMenu\" class=\"hidden absolute bottom-full left-2 right-2 mb-1 py-1.5 bg-slate-800 rounded-xl border border-slate-700 shadow-xl z-50\">\r\n");
      out.write("            <a href=\"profile.jsp\" class=\"flex items-center gap-2 px-3 py-2.5 rounded-lg text-slate-300 hover:bg-slate-700 text-sm transition-all duration-200\">Hồ Sơ Cá Nhân</a>\r\n");
      out.write("            <a href=\"UserController?action=logout\" class=\"flex items-center gap-2 px-3 py-2.5 rounded-lg text-red-400 hover:bg-red-500/20 text-sm transition-all duration-200\">Đăng Xuất</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<!-- Overlay for Mobile -->\r\n");
      out.write("<div id=\"sidebarOverlay\" class=\"fixed inset-0 bg-black/50 z-30 lg:hidden hidden\" onclick=\"toggleSidebar()\"></div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
