/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2026-04-09 08:16:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pms.model.DashboardDTO;
import pms.model.WorkOrderDTO;
import pms.model.ProductionLogDTO;
import pms.model.ItemDTO;
import pms.model.UserDTO;
import java.util.List;
import java.text.SimpleDateFormat;
import java.util.Date;
import pms.utils.NotificationService.Notification;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("pms.model.ProductionLogDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("pms.model.ItemDTO");
    _jspx_imports_classes.add("pms.model.UserDTO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("pms.model.DashboardDTO");
    _jspx_imports_classes.add("pms.model.WorkOrderDTO");
    _jspx_imports_classes.add("pms.utils.NotificationService.Notification");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    request.setCharacterEncoding("UTF-8");
    response.setCharacterEncoding("UTF-8");
    
    DashboardDTO data = (DashboardDTO) request.getAttribute("dashboardData");
    UserDTO user = (UserDTO) session.getAttribute("user");
    List<Notification> notifications = (List<Notification>) session.getAttribute("notifications");
    String userName = user != null ? user.getUsername() : "User";
    String userRole = user != null ? user.getRole() : "user";
    boolean isAdmin = "admin".equalsIgnoreCase(userRole);
    boolean isWorker = "employee".equalsIgnoreCase(userRole)
            || "worker".equalsIgnoreCase(userRole)
            || "user".equalsIgnoreCase(userRole);
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdfTime = new SimpleDateFormat("HH:mm");
    if (data == null) data = new DashboardDTO();
    if (notifications == null) notifications = new java.util.ArrayList<>();
    
    int unreadCount = 0;
    for (Notification n : notifications) {
        if (!n.isRead()) unreadCount++;
    }
    
    Boolean sessionDark = (Boolean) session.getAttribute("darkMode");
    boolean isDarkMode = sessionDark != null ? sessionDark : false;
    
    String lang = session.getAttribute("lang") != null ? (String) session.getAttribute("lang") : "vi";
    String activePage = "dashboard"; // Trang hiện tại cho sidebar
    String pageTitle = "Dashboard"; // Tiêu đề cho header
    request.setAttribute("activePage", activePage);
    request.setAttribute("pageTitle", pageTitle);
    
    boolean hasData = data.getTotalWorkOrders() > 0 || data.getTotalProductionLogs() > 0 || data.getTotalBills() > 0;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"");
      out.print( lang );
      out.write("\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard - PMS</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        tailwind.config = {\r\n");
      out.write("            darkMode: 'class',\r\n");
      out.write("            theme: {\r\n");
      out.write("                extend: {\r\n");
      out.write("                    fontFamily: {\r\n");
      out.write("                        sans: ['Inter', 'Segoe UI', 'Arial', 'sans-serif'],\r\n");
      out.write("                    },\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { font-family: 'Inter', 'Segoe UI', Arial, sans-serif; }\r\n");
      out.write("        body { overflow-x: hidden; }\r\n");
      out.write("        \r\n");
      out.write("        /* Sidebar cố định - cùng shared-sidebar */\r\n");
      out.write("        .sidebar-fixed {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            z-index: 40;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Logo cố định trong sidebar */\r\n");
      out.write("        .sidebar-header {\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            background: #0f172a;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Navigation scroll riêng */\r\n");
      out.write("        .sidebar-nav {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            scrollbar-width: thin;\r\n");
      out.write("            scrollbar-color: #475569 #1e293b;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-nav::-webkit-scrollbar {\r\n");
      out.write("            width: 4px;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-nav::-webkit-scrollbar-track {\r\n");
      out.write("            background: #1e293b;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-nav::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: #475569;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* User section cố định */\r\n");
      out.write("        .sidebar-footer {\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background: #0f172a;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Main content area */\r\n");
      out.write("        .main-wrapper {\r\n");
      out.write("            margin-left: 0;\r\n");
      out.write("            transition: margin-left 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        @media (min-width: 1024px) {\r\n");
      out.write("            .main-wrapper {\r\n");
      out.write("                margin-left: 280px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Dark mode styles */\r\n");
      out.write("        .dark body { background: #0f172a; color: #e2e8f0; }\r\n");
      out.write("        .dark .sidebar-fixed { background: #0f172a; }\r\n");
      out.write("        .dark .sidebar-header { background: #0f172a; }\r\n");
      out.write("        .dark .sidebar-footer { background: #0f172a; }\r\n");
      out.write("        \r\n");
      out.write("        /* KPI Card */\r\n");
      out.write("        .kpi-card { transition: all 0.2s ease; }\r\n");
      out.write("        .kpi-card:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(0,0,0,0.1); }\r\n");
      out.write("        .dark .kpi-card { background: #1e293b; border-color: #334155; }\r\n");
      out.write("        .dark .kpi-card:hover { box-shadow: 0 8px 30px rgba(0,0,0,0.3); }\r\n");
      out.write("        \r\n");
      out.write("        /* Chart container */\r\n");
      out.write("        .chart-container { position: relative; height: 280px; }\r\n");
      out.write("        \r\n");
      out.write("        /* Status badges */\r\n");
      out.write("        .status-new { background: #dbeafe; color: #1d4ed8; }\r\n");
      out.write("        .status-progress { background: #fef3c7; color: #b45309; }\r\n");
      out.write("        .status-done { background: #d1fae5; color: #047857; }\r\n");
      out.write("        .status-cancelled { background: #fee2e2; color: #b91c1c; }\r\n");
      out.write("        \r\n");
      out.write("        /* Notification badge animation */\r\n");
      out.write("        .notif-badge { animation: pulse 2s infinite; }\r\n");
      out.write("        @keyframes pulse {\r\n");
      out.write("            0%, 100% { opacity: 1; }\r\n");
      out.write("            50% { opacity: 0.5; }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Progress bar */\r\n");
      out.write("        .progress-bar {\r\n");
      out.write("            transition: width 0.5s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Search box */\r\n");
      out.write("        .search-box {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.05);\r\n");
      out.write("        }\r\n");
      out.write("        .search-box:focus-within {\r\n");
      out.write("            border-color: #14b8a6;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(20, 184, 166, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .dark .search-box {\r\n");
      out.write("            background: #1e293b;\r\n");
      out.write("            border-color: #334155;\r\n");
      out.write("        }\r\n");
      out.write("        .dark .search-box:focus-within {\r\n");
      out.write("            border-color: #14b8a6;\r\n");
      out.write("        }\r\n");
      out.write("        .dark .search-box input {\r\n");
      out.write("            color: #e2e8f0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Dark mode được xử lý bởi Tailwind `dark:` và [`web/js/common.js`](web/js/common.js) */\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-slate-100 text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-100\">\r\n");
      out.write("    <div class=\"min-h-screen flex\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/shared-sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div id=\"mainWrapper\" class=\"main-wrapper flex-1 flex flex-col min-h-screen min-w-0\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/shared-header.jsp", out, false);
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <main class=\"flex-1 overflow-y-auto p-4 lg:p-6 bg-slate-100 dark:bg-slate-900\">\r\n");
      out.write("                <!-- KPI Large Cards (3 cards) - Hàng đầu tiên -->\r\n");
      out.write("                <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4 mb-6\">\r\n");
      out.write("                    <!-- Lệnh Sản Xuất -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-2xl bg-white p-6 shadow-sm border-t-4 border-teal-500 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-start justify-between\">\r\n");
      out.write("                            <div class=\"flex-1\">\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400\">Lệnh Sản Xuất</p>\r\n");
      out.write("                                <p class=\"mt-2 text-4xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalWorkOrders() );
      out.write("</p>\r\n");
      out.write("                                <div class=\"flex items-center gap-2 mt-2\">\r\n");
      out.write("                                    <span class=\"text-xs text-emerald-600 font-medium flex items-center gap-1\">\r\n");
      out.write("                                        <svg class=\"w-3 h-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 10l7-7m0 0l7 7m-7-7v18\"/></svg>\r\n");
      out.write("                                        ");
      out.print( data.getWorkOrdersDone() );
      out.write(" hoàn thành\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-14 h-14 rounded-xl bg-teal-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-7 h-7 text-teal-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-4\">\r\n");
      out.write("                            <div class=\"mb-1 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400\">\r\n");
      out.write("                                <span>Tỷ lệ hoàn thành</span>\r\n");
      out.write("                                <span class=\"font-semibold\">");
      out.print( data.getCompletionRate() );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"h-2 w-full rounded-full bg-slate-100 dark:bg-slate-700\">\r\n");
      out.write("                                <div class=\"bg-teal-500 h-2 rounded-full progress-bar\" style=\"width: ");
      out.print( data.getCompletionRate() );
      out.write("%\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("                    <!-- Đơn Hàng -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-2xl bg-white p-6 shadow-sm border-t-4 border-blue-500 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-start justify-between\">\r\n");
      out.write("                            <div class=\"flex-1\">\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400\">Đơn Đặt Hàng</p>\r\n");
      out.write("                                <p class=\"mt-2 text-4xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalPurchaseOrders() );
      out.write("</p>\r\n");
      out.write("                                <div class=\"flex items-center gap-2 mt-2\">\r\n");
      out.write("                                    <span class=\"text-xs text-amber-600 font-medium flex items-center gap-1\">\r\n");
      out.write("                                        <svg class=\"w-3 h-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                                        ");
      out.print( data.getPurchaseOrdersPending() );
      out.write(" chờ xử lý\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-14 h-14 rounded-xl bg-blue-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-7 h-7 text-blue-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mt-4\">\r\n");
      out.write("                            <div class=\"mb-1 flex items-center justify-between text-xs text-slate-500 dark:text-slate-400\">\r\n");
      out.write("                                <span>Tỷ lệ hoàn thành</span>\r\n");
      out.write("                                <span class=\"font-semibold\">");
      out.print( data.getTotalPurchaseOrders() > 0 ? ((data.getTotalPurchaseOrders() - data.getPurchaseOrdersPending()) * 100 / data.getTotalPurchaseOrders()) : 0 );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"h-2 w-full rounded-full bg-slate-100 dark:bg-slate-700\">\r\n");
      out.write("                                <div class=\"bg-blue-500 h-2 rounded-full progress-bar\" style=\"width: ");
      out.print( data.getTotalPurchaseOrders() > 0 ? ((data.getTotalPurchaseOrders() - data.getPurchaseOrdersPending()) * 100 / data.getTotalPurchaseOrders()) : 0 );
      out.write("%\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Doanh Thu -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-2xl bg-white p-6 shadow-sm border-t-4 border-emerald-500 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-start justify-between\">\r\n");
      out.write("                            <div class=\"flex-1\">\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400\">Tổng Thu Nhập</p>\r\n");
      out.write("                                <p class=\"text-3xl font-bold text-emerald-600 mt-2\">");
      out.print( data.getFormattedRevenue() );
      out.write("</p>\r\n");
      out.write("                                <div class=\"flex items-center gap-2 mt-2\">\r\n");
      out.write("                                    <span class=\"text-xs text-emerald-600 font-medium flex items-center gap-1\">\r\n");
      out.write("                                        <svg class=\"w-3 h-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 10l7-7m0 0l7 7m-7-7v18\"/></svg>\r\n");
      out.write("                                        Đơn vị: VND\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-14 h-14 rounded-xl bg-emerald-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-7 h-7 text-emerald-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                    <!-- Worker: thay KPI quản trị bằng KPI cá nhân -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-2xl bg-white p-6 shadow-sm border-t-4 border-amber-500 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-start justify-between\">\r\n");
      out.write("                            <div class=\"flex-1\">\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400\">Nhật Ký SX</p>\r\n");
      out.write("                                <p class=\"mt-2 text-4xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalProductionLogs() );
      out.write("</p>\r\n");
      out.write("                                <div class=\"flex items-center gap-2 mt-2\">\r\n");
      out.write("                                    <span class=\"text-xs text-amber-600 font-medium flex items-center gap-1\">\r\n");
      out.write("                                        <svg class=\"w-3 h-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                                        ");
      out.print( data.getLogsToday() );
      out.write(" log hôm nay\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-14 h-14 rounded-xl bg-amber-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-7 h-7 text-amber-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"kpi-card rounded-2xl bg-white p-6 shadow-sm border-t-4 border-emerald-500 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-start justify-between\">\r\n");
      out.write("                            <div class=\"flex-1\">\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400\">Tỷ Lệ Hoàn Thành</p>\r\n");
      out.write("                                <p class=\"text-3xl font-bold text-emerald-600 mt-2\">");
      out.print( data.getCompletionRate() );
      out.write("%</p>\r\n");
      out.write("                                <div class=\"flex items-center gap-2 mt-2\">\r\n");
      out.write("                                    <span class=\"text-xs text-emerald-600 font-medium flex items-center gap-1\">\r\n");
      out.write("                                        <svg class=\"w-3 h-3\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                                        Theo công việc của bạn\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-14 h-14 rounded-xl bg-emerald-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-7 h-7 text-emerald-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (isAdmin) { 
      out.write("\r\n");
      out.write("                <!-- Status Cards (4 cards smaller) - Hàng thứ hai -->\r\n");
      out.write("                <div class=\"grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6\">\r\n");
      out.write("                    <!-- Lỗi -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-xl bg-white p-4 shadow-sm border-t-4 border-red-400 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase text-slate-500 dark:text-slate-400\">Lỗi Sản Phẩm</p>\r\n");
      out.write("                                <p class=\"mt-1 text-2xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalDefects() );
      out.write("</p>\r\n");
      out.write("                                <p class=\"mt-1 text-xs text-slate-400 dark:text-slate-500\">Danh mục lỗi</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-10 h-10 rounded-lg bg-red-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-5 h-5 text-red-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Nhật Ký -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-xl bg-white p-4 shadow-sm border-t-4 border-amber-400 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase text-slate-500 dark:text-slate-400\">Nhật Ký SX</p>\r\n");
      out.write("                                <p class=\"mt-1 text-2xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalProductionLogs() );
      out.write("</p>\r\n");
      out.write("                                <p class=\"mt-1 text-xs text-slate-400 dark:text-slate-500\">");
      out.print( data.getLogsToday() );
      out.write(" log hôm nay</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-10 h-10 rounded-lg bg-amber-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-5 h-5 text-amber-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Hoàn Thành -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-xl bg-white p-4 shadow-sm border-t-4 border-emerald-400 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"text-xs font-medium text-slate-500 uppercase\">Tỷ Lệ HT</p>\r\n");
      out.write("                                <p class=\"text-2xl font-bold text-emerald-600 mt-1\">");
      out.print( data.getCompletionRate() );
      out.write("</p>\r\n");
      out.write("                                <p class=\"mt-1 text-xs text-slate-400 dark:text-slate-500\">Tổng số lệnh SX</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-10 h-10 rounded-lg bg-emerald-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-5 h-5 text-emerald-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Hóa Đơn -->\r\n");
      out.write("                    <div class=\"kpi-card rounded-xl bg-white p-4 shadow-sm border-t-4 border-purple-400 dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"text-xs font-medium uppercase text-slate-500 dark:text-slate-400\">Hóa Đơn</p>\r\n");
      out.write("                                <p class=\"mt-1 text-2xl font-bold text-slate-800 dark:text-slate-100\">");
      out.print( data.getTotalBills() );
      out.write("</p>\r\n");
      out.write("                                <p class=\"mt-1 text-xs text-slate-400 dark:text-slate-500\">Tổng số hóa đơn</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"w-10 h-10 rounded-lg bg-purple-50 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-5 h-5 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Charts Row - Biểu đồ lớn -->\r\n");
      out.write("                <div class=\"grid lg:grid-cols-3 gap-6 mb-6\">\r\n");
      out.write("                    <!-- Revenue Chart -->\r\n");
      out.write("                    <div class=\"lg:col-span-2 rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <h3 class=\"text-base font-semibold text-slate-800 dark:text-slate-100\">Biểu Đồ Doanh Thu Theo Tháng</h3>\r\n");
      out.write("                            <span class=\"rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-700 dark:text-slate-300\">");
      out.print( new java.text.SimpleDateFormat("yyyy").format(new Date()) );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chart-container\">\r\n");
      out.write("                            <canvas id=\"revenueChart\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- WO Status Chart -->\r\n");
      out.write("                    <div class=\"rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <h3 class=\"text-base font-semibold text-slate-800 dark:text-slate-100\">Phân Bổ Trạng Thái WO</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chart-container\">\r\n");
      out.write("                            <canvas id=\"woStatusChart\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Quick Actions - Phần phụ -->\r\n");
      out.write("                <div class=\"rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                    <h3 class=\"mb-4 text-base font-semibold text-slate-800 dark:text-slate-100\">Thao Tác Nhanh</h3>\r\n");
      out.write("                    <div class=\"grid grid-cols-2 md:grid-cols-4 gap-4\">\r\n");
      out.write("                        <a href=\"MainController?action=addWorkOrder\" class=\"flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-4 transition-all hover:border-teal-300 hover:bg-teal-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-teal-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-teal-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 4v16m8-8H4\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"text-sm font-medium text-slate-700 dark:text-slate-200\">Tạo Lệnh SX</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"MainController?action=listProduction\" class=\"flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-4 transition-all hover:border-amber-300 hover:bg-amber-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-amber-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"text-sm font-medium text-slate-700 dark:text-slate-200\">Nhật Ký SX</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"MainController?action=listBill\" class=\"flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-4 transition-all hover:border-purple-300 hover:bg-purple-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-purple-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"text-sm font-medium text-slate-700 dark:text-slate-200\">Tạo Hóa Đơn</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"MainController?action=listPurchaseOrder\" class=\"flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-4 transition-all hover:border-blue-300 hover:bg-blue-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-blue-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"text-sm font-medium text-slate-700 dark:text-slate-200\">Đơn Đặt Hàng</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <!-- Worker summary -->\r\n");
      out.write("                <div class=\"grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6\">\r\n");
      out.write("                    <div class=\"rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <h3 class=\"text-base font-semibold text-slate-800 dark:text-slate-100\">Công việc gần đây</h3>\r\n");
      out.write("                            <span class=\"rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-700\">");
      out.print( data.getRecentWorkOrders() != null ? data.getRecentWorkOrders().size() : 0 );
      out.write(" việc</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 if (data.getRecentWorkOrders() != null && !data.getRecentWorkOrders().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"space-y-3\">\r\n");
      out.write("                                ");
 for (WorkOrderDTO workOrder : data.getRecentWorkOrders()) { 
      out.write("\r\n");
      out.write("                                <div class=\"rounded-xl border border-slate-200 p-4 dark:border-slate-700\">\r\n");
      out.write("                                    <div class=\"flex items-center justify-between gap-3\">\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <p class=\"font-semibold text-slate-800 dark:text-slate-100\">");
      out.print( workOrder.getProductName() != null ? workOrder.getProductName() : "Lệnh sản xuất #" + workOrder.getWo_id() );
      out.write("</p>\r\n");
      out.write("                                            <p class=\"text-xs text-slate-500 dark:text-slate-400\">Mã WO: ");
      out.print( workOrder.getWo_id() );
      out.write("</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"rounded-full px-2.5 py-1 text-xs font-semibold ");
      out.print( "Done".equalsIgnoreCase(workOrder.getStatus()) ? "status-done" : ("InProgress".equalsIgnoreCase(workOrder.getStatus()) ? "status-progress" : "status-new") );
      out.write('"');
      out.write('>');
      out.print( workOrder.getStatusLabel() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <p class=\"text-sm text-slate-500 dark:text-slate-400\">Chưa có công việc nào được giao.</p>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                        <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                            <h3 class=\"text-base font-semibold text-slate-800 dark:text-slate-100\">Nhật ký gần đây</h3>\r\n");
      out.write("                            <span class=\"rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700\">");
      out.print( data.getRecentLogs() != null ? data.getRecentLogs().size() : 0 );
      out.write(" log</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 if (data.getRecentLogs() != null && !data.getRecentLogs().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"space-y-3\">\r\n");
      out.write("                                ");
 for (ProductionLogDTO log : data.getRecentLogs()) { 
      out.write("\r\n");
      out.write("                                <div class=\"rounded-xl border border-slate-200 p-4 dark:border-slate-700\">\r\n");
      out.write("                                    <p class=\"font-semibold text-slate-800 dark:text-slate-100\">");
      out.print( log.getStepName() != null ? log.getStepName() : "Đã ghi nhận" );
      out.write("</p>\r\n");
      out.write("                                    <p class=\"text-xs text-slate-500 dark:text-slate-400\">WO: ");
      out.print( log.getWoId() );
      out.write(" • Số lượng: ");
      out.print( log.getProducedQuantity() );
      out.write("</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <p class=\"text-sm text-slate-500 dark:text-slate-400\">Hôm nay chưa có nhật ký sản xuất nào.</p>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"rounded-2xl bg-white p-6 shadow-sm dark:bg-slate-800\">\r\n");
      out.write("                    <h3 class=\"mb-4 text-base font-semibold text-slate-800 dark:text-slate-100\">Thao tác nhanh</h3>\r\n");
      out.write("                    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\r\n");
      out.write("                        <a href=\"MainController?action=listProduction\" class=\"flex items-center gap-3 rounded-xl border border-slate-200 p-4 transition-all hover:border-amber-300 hover:bg-amber-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-amber-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"font-medium text-slate-700 dark:text-slate-200\">Xem nhật ký sản xuất</p>\r\n");
      out.write("                                <p class=\"text-xs text-slate-500 dark:text-slate-400\">Theo dõi việc được giao và tiến độ cá nhân</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"MainController?action=listWorkOrder\" class=\"flex items-center gap-3 rounded-xl border border-slate-200 p-4 transition-all hover:border-teal-300 hover:bg-teal-50 dark:border-slate-700 dark:hover:bg-slate-700/70\">\r\n");
      out.write("                            <div class=\"w-12 h-12 rounded-xl bg-teal-100 flex items-center justify-center\">\r\n");
      out.write("                                <svg class=\"w-6 h-6 text-teal-600\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"/></svg>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <p class=\"font-medium text-slate-700 dark:text-slate-200\">Xem lệnh sản xuất</p>\r\n");
      out.write("                                <p class=\"text-xs text-slate-500 dark:text-slate-400\">Chỉ hiển thị danh sách công việc liên quan</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </main>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        ");
 if (hasData && isAdmin) { 
      out.write("\r\n");
      out.write("        const revenueCanvas = document.getElementById('revenueChart');\r\n");
      out.write("        const statusCanvas = document.getElementById('woStatusChart');\r\n");
      out.write("\r\n");
      out.write("        if (revenueCanvas) {\r\n");
      out.write("            const monthLabels = ['T1','T2','T3','T4','T5','T6','T7','T8','T9','T10','T11','T12'];\r\n");
      out.write("            const revenueData = new Array(12).fill(0);\r\n");
      out.write("            ");
 if (data.getMonthlyRevenue() != null) {
                for (double[] row : data.getMonthlyRevenue()) { 
      out.write("\r\n");
      out.write("                    revenueData[Math.floor(");
      out.print( row[0] );
      out.write(") - 1] = ");
      out.print( (long) row[1] );
      out.write(";\r\n");
      out.write("            ");
 } } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            new Chart(revenueCanvas.getContext('2d'), {\r\n");
      out.write("                type: 'bar',\r\n");
      out.write("                data: {\r\n");
      out.write("                    labels: monthLabels,\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        label: 'Doanh thu (VND)',\r\n");
      out.write("                        data: revenueData,\r\n");
      out.write("                        backgroundColor: 'rgba(20, 184, 166, 0.7)',\r\n");
      out.write("                        borderColor: 'rgba(20, 184, 166, 1)',\r\n");
      out.write("                        borderWidth: 1,\r\n");
      out.write("                        borderRadius: 6,\r\n");
      out.write("                    }]\r\n");
      out.write("                },\r\n");
      out.write("                options: {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    plugins: { legend: { display: false } },\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true,\r\n");
      out.write("                            ticks: { callback: function(value) {\r\n");
      out.write("                                if (value >= 1000000) return (value/1000000).toFixed(1) + 'M';\r\n");
      out.write("                                if (value >= 1000) return (value/1000).toFixed(0) + 'K';\r\n");
      out.write("                                return value;\r\n");
      out.write("                            }}\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (statusCanvas) {\r\n");
      out.write("            new Chart(statusCanvas.getContext('2d'), {\r\n");
      out.write("                type: 'doughnut',\r\n");
      out.write("                data: {\r\n");
      out.write("                    labels: ['Mới', 'Đang SX', 'Hoàn Thành', 'Đã Hủy'],\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        data: [");
      out.print( data.getWorkOrdersNew() );
      out.write(',');
      out.write(' ');
      out.print( data.getWorkOrdersInProgress() );
      out.write(',');
      out.write(' ');
      out.print( data.getWorkOrdersDone() );
      out.write(',');
      out.write(' ');
      out.print( data.getWorkOrdersCancelled() );
      out.write("],\r\n");
      out.write("                        backgroundColor: ['#3b82f6', '#f59e0b', '#10b981', '#ef4444'],\r\n");
      out.write("                        borderWidth: 0,\r\n");
      out.write("                    }]\r\n");
      out.write("                },\r\n");
      out.write("                options: {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    plugins: { legend: { position: 'bottom', labels: { padding: 16, font: { size: 12 } } } },\r\n");
      out.write("                    cutout: '60%',\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
