/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2026-04-09 08:16:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.String;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.lang.String");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Chống cache: buộc browser luôn tải lại trang login (tránh lộ trang sau logout)
    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    response.setHeader("Pragma", "no-cache");
    response.setDateHeader("Expires", 0);

    // Đọc thông báo lỗi và username từ session (nếu có – do UserController set sau login thất bại)
    String message = (String) session.getAttribute("loginMessage");
    String usernameValue = (String) session.getAttribute("loginUsername");
    if (usernameValue == null) {
        usernameValue = ""; // Tránh lỗi NullPointerException khi render value=""
    }

    // Xóa flash message khỏi session ngay sau khi đọc (chỉ hiển thị 1 lần)
    session.removeAttribute("loginMessage");
    session.removeAttribute("loginUsername");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("  Trang đăng nhập thật của project.\r\n");
      out.write("  - Không dùng JSTL để tránh lỗi thiếu thư viện trên Tomcat hiện tại.\r\n");
      out.write("  - Form submit trực tiếp tới `MainController` với action `loginUser`.\r\n");
      out.write("  - Nếu đăng nhập sai thì backend set `message` và trang này hiển thị lại thông báo lỗi.\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Sign In</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            :root {\r\n");
      out.write("                --bg: #f3f4f6;\r\n");
      out.write("                --surface: #ffffff;\r\n");
      out.write("                --surface-muted: #f8fafc;\r\n");
      out.write("                --border: #e5e7eb;\r\n");
      out.write("                --text: #111827;\r\n");
      out.write("                --text-muted: #6b7280;\r\n");
      out.write("                --text-inverse: #ffffff;\r\n");
      out.write("                --primary: #2563eb;\r\n");
      out.write("                --primary-hover: #1d4ed8;\r\n");
      out.write("                --primary-soft: #dbeafe;\r\n");
      out.write("                --danger: #dc2626;\r\n");
      out.write("                --danger-soft: #fee2e2;\r\n");
      out.write("                --shadow-sm: 0 1px 2px rgba(15, 23, 42, 0.06);\r\n");
      out.write("                --shadow-md: 0 4px 12px rgba(15, 23, 42, 0.1);\r\n");
      out.write("                --shadow-lg: 0 8px 24px rgba(15, 23, 42, 0.12);\r\n");
      out.write("                --radius-sm: 10px;\r\n");
      out.write("                --radius-md: 16px;\r\n");
      out.write("                font-family: Inter, \"Segoe UI\", Roboto, Arial, sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            * {\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            html,\r\n");
      out.write("            body {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                min-height: 100%;\r\n");
      out.write("                background: var(--bg);\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                font-family: inherit;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            button,\r\n");
      out.write("            input {\r\n");
      out.write("                font: inherit;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            a {\r\n");
      out.write("                color: inherit;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-shell {\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                display: grid;\r\n");
      out.write("                place-items: center;\r\n");
      out.write("                padding: 32px 16px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-card {\r\n");
      out.write("                width: min(100%, 820px);\r\n");
      out.write("                display: grid;\r\n");
      out.write("                grid-template-columns: 1fr 1fr;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("                background: var(--surface);\r\n");
      out.write("                border: 1px solid var(--border);\r\n");
      out.write("                border-radius: var(--radius-md);\r\n");
      out.write("                box-shadow: var(--shadow-lg);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-visual,\r\n");
      out.write("            .auth-form {\r\n");
      out.write("                padding: 48px 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-visual {\r\n");
      out.write("                background: var(--surface-muted);\r\n");
      out.write("                display: grid;\r\n");
      out.write("                place-items: center;\r\n");
      out.write("                border-right: 1px solid var(--border);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-visual img {\r\n");
      out.write("                width: min(100%, 180px);\r\n");
      out.write("                height: auto;\r\n");
      out.write("                object-fit: contain;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-title {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .section-subtitle {\r\n");
      out.write("                margin: 8px 0 0;\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                line-height: 1.6;\r\n");
      out.write("                font-size: 0.95rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            form {\r\n");
      out.write("                display: grid;\r\n");
      out.write("                gap: 20px;\r\n");
      out.write("                margin-top: 28px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .field-group {\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .field-label {\r\n");
      out.write("                display: block;\r\n");
      out.write("                margin-bottom: 8px;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-wrapper {\r\n");
      out.write("                position: relative;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-icon {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 14px;\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                pointer-events: none;\r\n");
      out.write("                transition: color 0.2s ease;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 13px 14px 13px 44px;\r\n");
      out.write("                border: 1.5px solid var(--border);\r\n");
      out.write("                border-radius: var(--radius-sm);\r\n");
      out.write("                background: var(--surface);\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("                font-size: 0.95rem;\r\n");
      out.write("                transition: border-color 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input::placeholder {\r\n");
      out.write("                color: #9ca3af;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input:focus {\r\n");
      out.write("                outline: none;\r\n");
      out.write("                border-color: var(--primary);\r\n");
      out.write("                box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.12);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input:focus + .input-icon,\r\n");
      out.write("            .input:focus ~ .input-icon {\r\n");
      out.write("                color: var(--primary);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .toggle-password {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                right: 12px;\r\n");
      out.write("                background: none;\r\n");
      out.write("                border: none;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                padding: 4px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                transition: color 0.2s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .toggle-password:hover {\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .auth-meta {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 12px;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .checkbox-wrapper {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .checkbox-wrapper input[type=\"checkbox\"] {\r\n");
      out.write("                width: 16px;\r\n");
      out.write("                height: 16px;\r\n");
      out.write("                accent-color: var(--primary);\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .checkbox-label {\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                user-select: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .forgot-link {\r\n");
      out.write("                color: var(--primary);\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                transition: color 0.2s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .forgot-link:hover {\r\n");
      out.write("                color: var(--primary-hover);\r\n");
      out.write("                text-decoration: underline;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn {\r\n");
      out.write("                display: inline-flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                padding: 13px 20px;\r\n");
      out.write("                border-radius: var(--radius-sm);\r\n");
      out.write("                border: 1px solid transparent;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                font-size: 0.95rem;\r\n");
      out.write("                transition: all 0.25s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-primary {\r\n");
      out.write("                background: linear-gradient(135deg, var(--primary) 0%, var(--primary-hover) 100%);\r\n");
      out.write("                color: var(--text-inverse);\r\n");
      out.write("                box-shadow: 0 2px 8px rgba(37, 99, 235, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-primary:hover {\r\n");
      out.write("                transform: translateY(-1px);\r\n");
      out.write("                box-shadow: 0 4px 16px rgba(37, 99, 235, 0.4);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-primary:active {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("                box-shadow: 0 2px 6px rgba(37, 99, 235, 0.3);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-alert {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-backdrop {\r\n");
      out.write("                position: fixed;\r\n");
      out.write("                inset: 0;\r\n");
      out.write("                background: rgba(15, 23, 42, 0.45);\r\n");
      out.write("                display: none;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                padding: 24px;\r\n");
      out.write("                z-index: 50;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-backdrop.is-open {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup {\r\n");
      out.write("                width: min(100%, 420px);\r\n");
      out.write("                background: var(--surface);\r\n");
      out.write("                border-radius: 22px;\r\n");
      out.write("                box-shadow: 0 24px 60px rgba(15, 23, 42, 0.22);\r\n");
      out.write("                border: 1px solid #fecaca;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("                animation: popupIn 0.22s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-head {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 12px;\r\n");
      out.write("                padding: 20px 22px 12px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-icon {\r\n");
      out.write("                width: 42px;\r\n");
      out.write("                height: 42px;\r\n");
      out.write("                border-radius: 999px;\r\n");
      out.write("                background: var(--danger-soft);\r\n");
      out.write("                color: var(--danger);\r\n");
      out.write("                display: inline-flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("                flex-shrink: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-title {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-subtitle {\r\n");
      out.write("                margin: 4px 0 0;\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                font-size: 0.92rem;\r\n");
      out.write("                line-height: 1.5;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-body {\r\n");
      out.write("                padding: 0 22px 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-message {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 14px 16px;\r\n");
      out.write("                border-radius: 14px;\r\n");
      out.write("                background: linear-gradient(180deg, #fff1f2 0%, #ffe4e6 100%);\r\n");
      out.write("                color: #9f1239;\r\n");
      out.write("                border: 1px solid #fecdd3;\r\n");
      out.write("                line-height: 1.6;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-actions {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: flex-end;\r\n");
      out.write("                padding: 0 22px 22px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-popup-close {\r\n");
      out.write("                min-width: 110px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes popupIn {\r\n");
      out.write("                from {\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                    transform: translateY(10px) scale(0.98);\r\n");
      out.write("                }\r\n");
      out.write("                to {\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                    transform: translateY(0) scale(1);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @media (max-width: 860px) {\r\n");
      out.write("                .auth-card {\r\n");
      out.write("                    grid-template-columns: 1fr;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .auth-visual {\r\n");
      out.write("                    border-right: 0;\r\n");
      out.write("                    border-bottom: 1px solid var(--border);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .auth-visual,\r\n");
      out.write("                .auth-form {\r\n");
      out.write("                    padding: 36px 28px;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"auth-shell\">\r\n");
      out.write("            <section class=\"auth-card\">\r\n");
      out.write("                <div class=\"auth-visual\">\r\n");
      out.write("                    <img src=\"img/logo.png\" alt=\"Application logo\" />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"auth-form\">\r\n");
      out.write("                    <h1 class=\"section-title\">Sign in</h1>\r\n");
      out.write("                    <p class=\"section-subtitle\">Enter your credentials to access your account.</p>\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"MainController\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"loginUser\"/>\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (message != null && !message.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"form-alert\">");
      out.print( message );
      out.write("</div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"field-group\">\r\n");
      out.write("                            <label class=\"field-label\" for=\"txtUsername\">Username</label>\r\n");
      out.write("                            <div class=\"input-wrapper\">\r\n");
      out.write("                                <input\r\n");
      out.write("                                    id=\"txtUsername\"\r\n");
      out.write("                                    class=\"input\"\r\n");
      out.write("                                    type=\"text\"\r\n");
      out.write("                                    name=\"txtUsername\"\r\n");
      out.write("                                    placeholder=\"Enter your username\"\r\n");
      out.write("                                    value=\"");
      out.print( usernameValue );
      out.write("\"\r\n");
      out.write("                                    required\r\n");
      out.write("                                    autocomplete=\"username\"\r\n");
      out.write("                                />\r\n");
      out.write("                                <span class=\"input-icon\">\r\n");
      out.write("                                    <svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("                                        <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"field-group\">\r\n");
      out.write("                            <label class=\"field-label\" for=\"txtPassword\">Password</label>\r\n");
      out.write("                            <div class=\"input-wrapper\">\r\n");
      out.write("                                <input\r\n");
      out.write("                                    id=\"txtPassword\"\r\n");
      out.write("                                    class=\"input\"\r\n");
      out.write("                                    type=\"password\"\r\n");
      out.write("                                    name=\"txtPassword\"\r\n");
      out.write("                                    placeholder=\"Enter your password\"\r\n");
      out.write("                                    required\r\n");
      out.write("                                    autocomplete=\"current-password\"\r\n");
      out.write("                                />\r\n");
      out.write("                                <span class=\"input-icon\">\r\n");
      out.write("                                    <svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                        <path d=\"M7 11V7a5 5 0 0 1 10 0v4\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <button class=\"toggle-password\" type=\"button\" onclick=\"togglePasswordVisibility()\" aria-label=\"Toggle password visibility\">\r\n");
      out.write("                                    <svg id=\"eyeIcon\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z\"></path>\r\n");
      out.write("                                        <circle cx=\"12\" cy=\"12\" r=\"3\"></circle>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg id=\"eyeOffIcon\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display:none\">\r\n");
      out.write("                                        <path d=\"M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24\"></path>\r\n");
      out.write("                                        <line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"></line>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"auth-meta\">\r\n");
      out.write("                            <label class=\"checkbox-wrapper\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"rememberMe\" id=\"rememberMe\" />\r\n");
      out.write("                                <span class=\"checkbox-label\">Remember me</span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <a href=\"#\" class=\"forgot-link\">Forgot password?</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"btn btn-primary\" type=\"submit\">Sign in</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (message != null && !message.trim().isEmpty()) { 
      out.write("\r\n");
      out.write("            <div id=\"loginErrorPopup\" class=\"login-popup-backdrop is-open\">\r\n");
      out.write("                <div class=\"login-popup\" role=\"alertdialog\" aria-modal=\"true\" aria-labelledby=\"loginErrorTitle\">\r\n");
      out.write("                    <div class=\"login-popup-head\">\r\n");
      out.write("                        <div class=\"login-popup-icon\">!</div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h2 id=\"loginErrorTitle\" class=\"login-popup-title\">Sign in failed</h2>\r\n");
      out.write("                            <p class=\"login-popup-subtitle\">Please check your username and password, then try again.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"login-popup-body\">\r\n");
      out.write("                        <p class=\"login-popup-message\">");
      out.print( message );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"login-popup-actions\">\r\n");
      out.write("                        <button id=\"loginPopupClose\" class=\"btn btn-primary login-popup-close\" type=\"button\">Try again</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function togglePasswordVisibility() {\r\n");
      out.write("                var passwordInput = document.getElementById('txtPassword');\r\n");
      out.write("                var eyeIcon = document.getElementById('eyeIcon');\r\n");
      out.write("                var eyeOffIcon = document.getElementById('eyeOffIcon');\r\n");
      out.write("\r\n");
      out.write("                if (passwordInput.type === 'password') {\r\n");
      out.write("                    passwordInput.type = 'text';\r\n");
      out.write("                    eyeIcon.style.display = 'none';\r\n");
      out.write("                    eyeOffIcon.style.display = 'block';\r\n");
      out.write("                } else {\r\n");
      out.write("                    passwordInput.type = 'password';\r\n");
      out.write("                    eyeIcon.style.display = 'block';\r\n");
      out.write("                    eyeOffIcon.style.display = 'none';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            (function () {\r\n");
      out.write("                var popup = document.getElementById('loginErrorPopup');\r\n");
      out.write("                var closeButton = document.getElementById('loginPopupClose');\r\n");
      out.write("                var usernameInput = document.getElementById('txtUsername');\r\n");
      out.write("                var passwordInput = document.getElementById('txtPassword');\r\n");
      out.write("\r\n");
      out.write("                function focusLoginField() {\r\n");
      out.write("                    if (passwordInput) {\r\n");
      out.write("                        passwordInput.focus();\r\n");
      out.write("                    } else if (usernameInput) {\r\n");
      out.write("                        usernameInput.focus();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (popup) {\r\n");
      out.write("                    function closePopup() {\r\n");
      out.write("                        popup.classList.remove('is-open');\r\n");
      out.write("                        focusLoginField();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if (closeButton) {\r\n");
      out.write("                        closeButton.addEventListener('click', closePopup);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    popup.addEventListener('click', function (event) {\r\n");
      out.write("                        if (event.target === popup) {\r\n");
      out.write("                            closePopup();\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    document.addEventListener('keydown', function (event) {\r\n");
      out.write("                        if (event.key === 'Escape' && popup.classList.contains('is-open')) {\r\n");
      out.write("                            closePopup();\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                window.addEventListener('pageshow', function (event) {\r\n");
      out.write("                    if (event.persisted) {\r\n");
      out.write("                        window.location.replace('login.jsp');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }());\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
